service: aiidea-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  hello:
    handler: handler.handler
    events:
      - httpApi:
          path: /tweet
          method: get
